name: Ecommerece CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore EcommerceIntegrationAPI.sln

    - name: Build
      run: dotnet build EcommerceIntegrationAPI.sln --no-restore

    - name: Run Tests
      run: dotnet test EcommerceIntegrationAPI.sln --no-build --verbosity normal
